### ISSUE TITLE
API Uptime response time is incorrect

### ISSUE THREAD

**Issue by bruceywang** [Brightergy/ex_gecko#18]
It should be using Runscope's "execute time" but instead I believe its using the runtime of the entire test.  The runscope api allows you to parse the JSON data and get the time it took to execute.
![screen shot 2016-10-06 at 1 52 08 pm](https://cloud.githubusercontent.com/assets/2660308/19166154/184cf402-8bcc-11e6-8e07-196ade0a0598.png)

**Comment by njdu** [comment]
I've looked into this, and it doesn't appear to be a parsing issue within Ex_Gecko.  For a runscope test result, "finished_at" returns the completion time of the entire test, including all overhead involved on the Runscope side. 

To get an a more accurate response time of the API calls, I can write a function that requests details for each individual step of a test, and then averages the response time together. What's annoying however, is that you can't request all the step results at once. For an N-step test, you have to make N requests to runscope.

An alternative is to require test step to checks the response time as a validation. When you do this, the validation results for each test step are available in a single request for the test Result

![image](https://cloud.githubusercontent.com/assets/10089896/19319615/a13f13ae-907b-11e6-9f12-f391378c4f79.png)

**Comment by njdu** [comment]
In #21, I implemented the first of the above two options, so that runscope tests are not constrained to check for response time.
